### PR TITLE
Unify code style and line endings

### PR DESCRIPTION
**Pull request by arturo182**

### CODE REVIEW

**Comment by simonvik** [comment]
I dont see the reason for `s/\\n/\\r\\n/`, do you want to build for windows?

**Comment by frazz** [comment]
It's common when you write to a UART. But on desktop programs it's more common with only \n.

On May 11, 2018 12:17:26 PM GMT+02:00, "Simon Vikström" <notifications@github.com> wrote:
>I dont see the reason for s/\\n/\\r\\n/, do you want to build for
>windows? 
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/xil-se/xildebug_cli/pull/11#issuecomment-388323478

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by arturo182** [comment]
Poor @frazz getting all email spam.

**Review by simonvik — APPROVED** [review]
I'm all happy

**Pull request merged**
